var dinner =  [
    {
      "name": "Salmon with Grapefruit and Lentil salad",
      "price": "$9.99",
      "text": "How we dream about our future",
      "key": "NA1",
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "picture": "../fakedata/Dinner/dinner6.png",
    },
    {
      "name": "Lemony salmon Piccata",
      "price":"$10.99",
      "text": "How we dream about our future",
      "key": "NA2",
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "picture": "../fakedata/Dinner/dinner2.png",
    },
    {
      "name": "Baked Chiken",
      "price": "$9.99",
      "text": "How we dream about our future",
      "key": "NA1",
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "picture": "../fakedata/Dinner/dinner1.png",
    },
    {
      "name": "Pork Tenderloin With Quinoa Pilaf",
      "price": "$12.99",
      "text": "How we dream about our future",
      "key": "NA1",
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "picture": "../fakedata/Dinner/dinner5.png",
    },
    {
      "name": "French fried with chines",
      "price": "$19.99",
      "text": "How we dream about our future",
      "key": "NA1",
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "picture": "../fakedata/Dinner/dinner4.png",
    },
    {
      "name": "Garlic butter baked salmon",
      "price": "$7.99",
      "text": "How we dream about our future",
      "key": "NA1",
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "picture": "../fakedata/Dinner/dinner3.png",
    }
  ]
  export default dinner;